INSERT INTO course (id, type, code, name, level, credit_hours) VALUES (1, 'ACT', '101', 'Tree Climbing', 'Undergraduate', 1);
INSERT INTO course (id, type, code, name, level, credit_hours) VALUES (2, 'HUM', '102', 'Getting Dressed', 'Undergraduate', 3);
INSERT INTO course (id, type, code, name, level, credit_hours) VALUES (3, 'HUM', '103', 'How to Go Outside', 'Undergraduate', 2);
INSERT INTO course (id, type, code, name, level, credit_hours) VALUES (4, 'GEN', '104', 'Cryptozoology', 'Undergraduate', 3);
INSERT INTO course (id, type, code, name, level, credit_hours) VALUES (5, 'LNG', '105', 'Elvish', 'Graduate', 3);
INSERT INTO course (id, type, code, name, level, credit_hours) VALUES (6, 'HUM', '106', 'Enjoying Sunshine', 'Graduate', 4);
INSERT INTO course (id, type, code, name, level, credit_hours) VALUES (7, 'SCI', '107', 'Cosmology Basics', 'Graduate', 6);
INSERT INTO course (id, type, code, name, level, credit_hours) VALUES (8, 'UNK', '108', 'Everything about Nothing', 'Graduate', 5);
INSERT INTO course (id, type, code, name, level, credit_hours) VALUES (9, 'UNK', '109', 'Nothing about Everything', 'Graduate', 3);
INSERT INTO course (id, type, code, name, level, credit_hours) VALUES (10, 'ACT', '110', 'History of Skateboarding', 'Graduate', 5);